import 'package:flutter/material.dart';

class ColorUtils {
  static Color background = const Color(0xffE5E5E5);
  static Color gradient1 = const Color(0xff246BFD);
  static Color gradient2 = const Color(0xff5089FF);
  static Color white = const Color(0xffffffff);
  static Color black = const Color(0xff111111);
  static Color mainColor = const Color(0xff246BFD);
  static Color contentSecondary = const Color(0xff555555);
  static Color grayscale70 = const Color(0xff78828A);
  static Color grayScale200 = const Color(0xffEEEEEE);
  static Color contentPrimary = const Color(0xff2B2B2B);
  static Color contentSecondaryInvarse = const Color(0xffF8F8F8);
  static Color textfieldBg = const Color(0xffF4F6F9);
  static Color hintTextColor = const Color(0xff94A3B8);
  static Color primary50 = const Color(0xffEEF5FF);
  static Color grayScale500 = const Color(0xff64748B);
  static Color contentTertiary = const Color(0xff717171);
  static Color contentDisable = const Color(0xffE8E7F1);
  static Color red = const Color(0xffF75555);
  static Color primary100 = const Color(0xffDAE8FF);
  static Color shadeFO = const Color(0xffF0F0F0);
  static Color bgPrimary = const Color(0xffF6F8FA);
  static Color darkRed = const Color(0xffFF0000);
  static Color gray900 = const Color(0xff101623);
  static Color blue700 = const Color(0xff0064E5);
  static Color neutrals = const Color(0xff353945);
  static Color black100 = const Color(0xff1E293B);
  static Color yellow = const Color(0xffFFD016);
  static Color contentPrimaryInvarse = const Color(0xffF4F4F4);
  static Color gray01 = const Color(0xffA7A9B7);
  static Color green = const Color(0xff38AC55);
  static Color marun = const Color(0xffB22525);
  static Color neutrals6 = const Color(0xffE6E8EC);
  static Color grayButtonShade = const Color(0xffE5E7EB);
  static Color primary200 = const Color(0xffBDD8FF);
  static Color rating = const Color(0xffFFBA55);
  static Color ofWhite = const Color(0xffF9FAFB);
  static Color greenActive = const Color(0xff1DA02A);
  static Color blackShade = const Color(0xff6C6C6C);
  static Color otherRed = const Color(0xffFF442B);
  static Color purple = const Color(0xffABB1E3);
  static Color purpleShadeLight = const Color(0xffA1A5C1);
}
